### ISSUE TITLE
Nav bar is wrongly aligned

### ISSUE THREAD

**Issue by jfilter** [okfde/offenegesetze.de#20]

**Comment by jfilter** [comment]
and why is kontakt now shown on desktop? it should only be visible on mobile.

**Comment by stefanw** [comment]
Why? When you have less space you show more stuff?

**Comment by jfilter** [comment]
No, UI is not showing as many items as possible. It's enough in the footer.

**Comment by jfilter** [comment]
![screen shot 2018-11-27 at 14 46 08](https://user-images.githubusercontent.com/3450307/49085811-31696c00-f253-11e8-9e1c-c9a3659a2835.png)

**Comment by stefanw** [comment]
Then why show it on mobile / at all? Navbar is now aligned on widescreen and fullhd breakpoints.

**Comment by jfilter** [comment]
Okay, it's good. Kontakt stays.
