### ISSUE TITLE
Wo sind die Gesetze?

### ISSUE THREAD

**Issue by antifa-ev** [okfde/offenegesetze.de#25]
Wo sind die Gesetze? Weder hier noch in https://github.com/okfde/api.offenegesetze.de/ gibt es die Volltexte als HTML.

**Comment by antifa-ev** [comment]
@arnese Wen interessieren die PDFs? Soll ich mir die Volltexte selber per pdftotext extrahieren? Das wäre deine Aufgabe gewesen. →Arne Semsrott - eine totale Fehlbesetzung.

**Comment by sebs** [comment]
Der Text ist in den files recht strukturiert enthalten, ich habe begonnen für einen Downloader zu bauen und die Extraktion war eigentlich als nächstes dran. 

Wenn der Antifa. EV., wie alle anderen hier  auch, etwas freundlicher ist, dann veröffentliche ich es, ansonsten warte ich bis Ende des Urlaubs in der Winterdatsche (Ende Juni) m. Es ist auf jeden fall nicht sehr schwer. 

Die Implementierung von parsern, für die einzelnen Dateien wird uns aber nicht erspart werden. 

p.s. Der Import in "Open Semantic Search" war so schwer erst mal nicht. Da kann man dann auch volltext suchen. Ist aber schwerer als sich im Bugtracker zu beschweren ;))))

**Comment by baerbock** [comment]
@jfilter Die Antifa ist einfach gegen Deutschland. Ich würde mich nicht mit diesem Konto abgeben.

**Comment by jfilter** [comment]
Okay.
