### ISSUE TITLE
RSS feed link anchors are invalid

### ISSUE THREAD

**Issue by Quintus** [okfde/offenegesetze.de#43]
The [RSS feed for BGBl I](https://api.offenegesetze.de/v1/veroeffentlichung/?format=rss&kind=bgbl1) contains invalid page anchors. For instance, 

> Gesetz zur Änderung des Grundgesetzes (Artikel 104b, 104c, 104d, 125c, 143e)

came linked as

> https://offenegesetze.de/veroeffentlichung/bgbl1/2019/11#page=404

But that's wrong. Correct is

> https://offenegesetze.de/veroeffentlichung/bgbl1/2019/11#page=4

Appearently the RSS feed uses BGBl's absolute page numbers, where it should use offenegesetze.de's relative line numbers.

**Comment by jfilter** [comment]
Yeah, thanks for pointing this out. The page numbers were wrongly calculated for 2019. It should be fixed now. If not, please re-open this issue.
