### ISSUE TITLE
Bedeutende Amstsblätter raussuchen

### ISSUE THREAD

**Issue by jfilter** [okfde/offenegesetze.de#8]

**Comment by arnese** [comment]
- Grundgesetz (https://offenegesetze.de/veroeffentlichung/bgbl1-1949-1-1/?q=grundgesetz#page=1)
- Ehe für alle (https://offenegesetze.de/veroeffentlichung/bgbl1-2017-52-9/?q=Gesetz%20zur%20Einf%C3%BChrung%20des%20Rechts%20auf%20Eheschlie%C3%9Fung%20f%C3%BCr%20Personen%20gleichen%20Geschlechts#page=59)
- Informationsfreiheitsgesetz (https://offenegesetze.de/veroeffentlichung/bgbl1-2005-57-1/?q=Informationsfreiheitsgesetz#page=2)
- Urheberrechtsgesetz (https://offenegesetze.de/veroeffentlichung/bgbl1-1965-51-1/?q=urheberrechtsgesetz#page=1)
- Strafbarkeit von Vergewaltigung in der Ehe (https://offenegesetze.de/veroeffentlichung/bgbl1-1998-6-5/?q=strafbarkeit%20vergewaltigung#page=24)
